# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0005_auto_20170218_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladdress',
            name='zipcode',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='zipcode',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
