# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0006_auto_20170218_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladdress',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
