# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0007_auto_20170218_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='insurance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitial', to='HackNYU.Insurance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='HackNYU.Insurance'),
        ),
    ]
