# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0008_auto_20170218_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
    ]
