# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0009_remove_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department',
            new_name='specialty',
        ),
    ]
