# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HackNYU', '0010_auto_20170218_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='inpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField(auto_now_add=True)),
                ('date_of_discharge', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('illness', models.CharField(max_length=30, verbose_name='Illness')),
                ('treatment', models.CharField(max_length=30, verbose_name='Treatment')),
                ('weight', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab', to='HackNYU.Patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='outpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outpatient', to='HackNYU.LabReport')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outpatient', to='HackNYU.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('roomtype', models.CharField(max_length=30, verbose_name='Room')),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='insurance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital', to='HackNYU.Insurance'),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient', to='HackNYU.LabReport'),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient', to='HackNYU.Patient'),
        ),
    ]
