# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0011_auto_20170218_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='HackNYU.Hospital'),
            preserve_default=False,
        ),
    ]
