# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0012_doctor_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='illness',
            field=models.CharField(max_length=500, verbose_name='Illness'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='treatment',
            field=models.CharField(max_length=500, verbose_name='Treatment'),
        ),
    ]
