# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0014_auto_20170218_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=50, verbose_name='Name'),
        ),
    ]
