# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0015_auto_20170218_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladdress',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='HackNYU.Hospital'),
        ),
    ]
