# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0017_auto_20170219_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
