# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackNYU', '0018_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
